### ISSUE TITLE
Issue when not using a template for the Root instance

### ISSUE THREAD

**Issue by Norbz** [scottbedard/oc-vuetober-theme#19]
Hey there.
I sent you an email about this one, but I figured it out, so i'm back here with the solution.
I tweaked Vuetober so I could have a layout that would load my components but not using the Router.

So now I have in my Main.js :

new Vue({
        el: '#app',
        data: {},
});

With the DOM being generated by October inside div#app.
I was getting this strange behavior where the dom were being completely erased when creating the Vue instance.

Turns out the Webpack configuration is using the wrong vue bundle. It's compiling using vue.js, and according to Vue docs this bundle is supposed to be used as a UMD module, but isn't meant to be compiled with Webpack.

They do provide a vue.esm.js file when pulling Vue with NPM.

The solution is to declare an alias in webpack.base.conf.js as following :

'vue$': 'vue/dist/vue.esm.js',

That's it.
Now you can recompile, and Vue will work as expected when not using the render function.

Hope you can fix it. Ill be happy to discuss the details with you.

**Comment by scottbedard** [comment]
Hi, so if I'm understanding your issue correctly, you want the root vue instance to come from your october backend? That should be doable.

The reason I'm not using `vue.esm.js` is to take advantage of Vue's "runtime only" build. Since this theme pre-compiles all of it's templates, there is no need to include the compiler in our production assets.

To do what you need, you'll need to use the "runtime + compiler" version of Vue, which is approximately 30% heavier than the current version we're using. But you are correct, this is the version you'll need to use if you want your root template to be served from your October site. [This page](https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only) has a bit more information about the "runtime only" vs "runtime + compiler" versions of Vue.
