### ISSUE TITLE
Multiple Themes

### ISSUE THREAD

**Issue by VitruxPT** [scottbedard/oc-vuetober-theme#2]
Hey, 

I started working with Vue today and i installed this Theme to work with it.

My question is: Can this theme work with other installed themes?

I already have another theme with all my pages that i don't want to work as an SPA which i've been working for months with my team and we decided to have the Dashboard for our users in an SPA style and right now we don't really know what to do with 2 themes. (Only domain.com/dashboard/ would be an SPA)

Since October can only have 1 active theme, there is no way for us to really work with both right? (I thought about the multisite plugin but it doesn't work anymore so that's not an option now).

**Comment by scottbedard** [comment]
Yes, this should be possible by modifying the theme.htm file. By default, it is set up to catch *all* routes, but you could change it to read `/dashboard/:all?*` to catch only your dashboard urls.

https://github.com/scottbedard/oc-vuetober-theme/blob/master/template/src/theme.htm#L2

Outside of that, just use normal October layouts, pages, partials, etc...

**Comment by VitruxPT** [comment]
To do that i should also copy the pages, layouts, partials and assets folders from our main theme to this one right in `/themes/SPA/src/` (or the other way around)?

**Comment by scottbedard** [comment]
Either or, it doesn't really matter. I would recommend doing it the way you mentioned though so you don't have to mess with any of the build configuration.

**Comment by VitruxPT** [comment]
I'm just having a problem right now.
I changed the root.vue file and the pages in the pages folder in `/themes/my-theme/src` but it is still showing me the intro page when i visit the url i set.

Are there any other files i need to remove/edit that i can't find?

**Comment by scottbedard** [comment]
You shouldn't have to change the `root.vue` file to achieve what you're after. Simply changing the `url` property of `/src/theme.htm` should do it.

Once this is done, you'll need to rebuild your theme with the following command.

```bash
$ npm run build
```

**Comment by VitruxPT** [comment]
Oh ok, i got it to work now, thanks. (I'm still new to this suff)

Just to make sure, now to work on my app i just need to work on the `pages/theme.htm` file right?

**Comment by scottbedard** [comment]
Your crossed out text is correct. The `theme.htm` file is like your layout, and the `.vue` files are what hold your actual content.

Sorry to hear that the learning curve was too high for you, I see how it can be a lot to take in at once. Hopefully soon I'll make some screencasts to go with this theme.

**Comment by VitruxPT** [comment]
Quick question that i couldn't quite figure out on my own before:

Is there a way to prevent the folder `/themes/my-theme/assets` from being cleared when we run the command `$ npm run build` since the other pages that are not from vue use that folder to retrieve other assets besides the ones that `vue` uses with `webpack`?

**Comment by scottbedard** [comment]
Yes and no. You can't prevent the webpack assets directory from being cleared, because it needs to kill off old assets. But you *can* change the directory that webpack is using by modifying these lines

https://github.com/scottbedard/oc-vuetober-theme/blob/master/template/build/webpack.base.conf.js#L15-L16

If you just append `/spa` or whatever onto the end of that, it should create a nice isolated area for your webpack assets to live.

**Comment by VitruxPT** [comment]
I did that and ran `$ npm run build` he still cleared the assets folder and created a folder named "pages" with the theme.htm inside

**Comment by scottbedard** [comment]
Creating the `/pages/theme.htm` is required. You can name that file anything you want, but your SPA still needs a single entry point, which is what that file provides.
https://github.com/scottbedard/oc-vuetober-theme/blob/master/template/build/webpack.prod.conf.js#L56

As for clearing out the `/assets` folder, you changed the output directory and it's still clearing it? Something might be messed up in your build config, because it's set up to only clear the directly it's outputting to.

**Comment by VitruxPT** [comment]
Changing the path doesn't prevent the folder `assets` from being deleted. I even tried renaming the folder in the config to `assets_spa` an create an empty folder names `assets` but it still deleted the folder `assets` and created another folder named `assets_spa`
